shutdown_costmaps: false

controller_frequency: 5.0
controller_patience: 5.0

planner_frequency: 0.0
planner_patience: 5.0

oscillation_timeout: 0.0 #infinite time
oscillation_distance: 0.2

recovery_behavior_enabled: false # true
clearing_rotation_allowed: false # true

base_local_planner: "iri_simulated_person_companion_akp_local_planner/AkpLocalPlanner"
#alternatives: base_local_planner/TrajectoryPlannerROS, dwa_local_planner/DWAPlannerROS
base_global_planner: "navfn/NavfnROS"
#alternatives: navfn/NavfnROS, global_planner/GlobalPlanner, carrot_planner/CarrotPlanner

